name: 'GitHub Actions Weather Bot'

on:
  push:  
    #branches:    
      #- master
    schedule:
      - cron: '0 22 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Result'
        run: bash ./weather.sh
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: '812634676@qq.com'
          password: 'mkgvgcygelxybehh'
          subject: ShenZhen Weather Report
          body: file://result.html
          to: '837109200@qq.com,812634676@qq.com,435119880@qq.com,1904390016@qq.com'
          from: GitHub Actions
          content_type: text/html