name: 'GitHub Actions Weather Bot'

on:
  push:  
    branches:    
      - master
    schedule:
      - cron: '0 22 * * *'

jobs:
  bot1:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Result'
        run: bash ./shell/weather.sh
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          erver_address: smtp.qq.com
          server_port: 465
          username: '812634676@qq.com'
          password: 'mkgvgcygelxybehh'
          subject: Weather Report
          body: file://index.html
          to: '812634676@qq.com'
          from: GitHub Actions
          content_type: text/html  
